export const AUTH_START = 'AUTH_START'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT'

export const FETCH_POSTS = 'FETCH_POSTS'